
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-app
spec:
  selector:
    app: hello-docker-app
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-app
spec:
  selector:
    matchLabels:
      app: hello-docker-app
  template:
    metadata:
      labels:
        app: hello-docker-app
    spec:
      containers:
      - name: hello-docker-app
        image: hello-docker-app/gulcan82:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000



